
# 错误处理相关
server.error.include-stacktrace: on_trace_param
#server.error.path: /error

# template 相关
#spring.thymeleaf.prefix: classpath:/templates/



security.basic.enabled: false
security.user.password: 123456

logging.level.org.springframework.web: INFO
logging.level.org.springframework.security: INFO
logging.level.org.springframework.boot.actuate.audit.listener.AuditListener: DEBUG
logging.level.org.springframework.boot.web.support.ErrorPageFilter: DEBUG
logging.level.org.springframework.web.servlet.view.ContentNegotiatingViewResolver: DEBUG
logging.level.org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping: DEBUG
# 用来追踪 restTemplate 请求
logging.level.org.apache.http: DEBUG

spring.devtools.restart.exclude: static/**,public/**,templates/**,resources/**


# JerseyProperties
# http://docs.spring.io/spring-boot/docs/1.5.1.RELEASE/reference/htmlsingle/#boot-features-jersey
# https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5#adding-the-dependencies-to-your-application
spring.jersey:
  application-path: /api
  type: servlet
  servlet.load-on-startup: -1
  init:
    "jersey.config.server.provider.packages": |
      io.swagger.jaxrs.listing,
      me.test.first.spring.boot.jersey
    # "jersey.config.server.provider.classnames": |
    #  io.swagger.jaxrs.listing.ApiListingResource,
    #  io.swagger.jaxrs.listing.SwaggerSerializers,
    #  {your.application.classes}

spring.jackson.default-property-inclusion: non_null