---
grails:
    profile: web
    codegen:
        defaultPackage: my.grails3
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

---
grails:
    gorm:
        failOnError: true

---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED






---
grails:
    mongodb:
        #host: 192.168.0.12
        #port: 27017
        #replicaSet:
        #    - "localhost:27017"
        #    - "localhost:27018"
        #connectionString: "mongodb://192.168.0.12:27017/zll"

        host: 127.0.0.1
        port: 12345
        #connectionString: "mongodb://localhost:12345/local"
        #username: zll
        #password: zll
        databaseName: local
        options:
            #ssl: true
            autoConnectRetry: true
            connectTimeout: 300
        default:
            mapping:
                version: true

---
# Spring Security 相关配置
#
#grails:
#    plugin:
#        springsecurity:
#            logout:
#                postOnly: false
#            password:
#                algorithm: 'bcrypt'
#                encodeHashAsBase64: true
#                bcrypt:
#                  logrounds: 7
#            userLookup:
#                userDomainClassName: "my.grails3.MyUser"
#            rejectIfNoRule: false
#            fii:
#                rejectPublicInvocations: false
#            securityConfigType: "Annotation"
#            successHandler:
#                defaultTargetUrl: "/"
#            providerNames:
#                - "daoAuthenticationProvider"
#                - "anonymousAuthenticationProvider"
#                - "rememberMeAuthenticationProvider"
#            secureChannel:
#                useHeaderCheckChannelSecurity: true
#            useSecurityEventListener: true
#            useSessionFixationPrevention: true
#            exceptionMappings:
#                'org.springframework.security.authentication.LockedException'             : '/user/accountLocked'
#                'org.springframework.security.authentication.DisabledException'           : '/user/accountDisabled'
#                'org.springframework.security.authentication.AccountExpiredException'     : '/user/accountExpired'
#                'org.springframework.security.authentication.CredentialsExpiredException' : '/user/passwordExpired'
#            useRoleGroups: false
#            authority:
#              groupAuthorityNameField:

a.b.c: "abc111"
environments:
   development:
      grails.logging.jul.usebridge: true
      grails.plugin.springsecurity.debug.useFilter: true
   production:
      grails.logging.jul.usebridge: false


spring.data.elasticsearch:
    cluster-name: "elasticsearch"
    cluster-nodes: "test13.kingsilk.xyz:9300"
    properties:
        "client.transport.ignore_cluster_name": true
        "client.transport.nodes_sampler_interval": "5s"
        "client.transport.ping_timeout": "5s"
        "client.transport.sniff": true
    repositories.enabled: false