server.port: 10004
spring.devtools.restart.exclude: static/**,public/**,templates/**,resources/**


logging.level.org.springframework.security: INFO
logging.level.org.springframework.boot.actuate.audit.listener.AuditListener: DEBUG
logging.level.org.springframework.security.config.annotation.authentication.configuration: DEBUG
logging.level.org.springframework.security.web.access: DEBUG
logging.level.org.springframework.security.web.csrf: DEBUG
logging.level.org.springframework.security.access: DEBUG
# 用来追踪 restTemplate 请求
logging.level.org.apache.http.wire: DEBUG
logging.level.me.test.oauth2.client: DEBUG
logging.level.org.springframework.boot.context.config.ConfigFileApplicationListener: TRACE
logging.level.me.test.oauth2: DEBUG


my.oauth2:
  auth:
    url:                    http://a.localhost:10001
    accessTokenUri:         http://a.localhost:10001/oauth/token
    userAuthorizationUri:   http://a.localhost:10001/oauth/authorize
    checkTokenUri:          http://a.localhost:10001/oauth/check_token
    realm: btpka3/oauth2
  resource:
    id:                     RSC_ID_rsc_server
    url:                    http://r.localhost:10002
    photoListUri:           http://r.localhost:10002/o2/photo
    username4AuthServer:    a_my_rsc
    password4AuthServer:    a_my_rsc
  client:
    id:                     CLIENT_ID_client_sso
    secret:                 CLIENT_PWD_client_sso
    url:                    http://s.localhost:10004
    scopes:
      - read
      - write
      - LOGIN
    authorizedGrantTypes:
      - authorization_code
      - implicit
      - client_credentials
      - password
      - refresh_token
    authorities:
      - ROLE_CLIENT
    preEstablishedRedirectUri:  ""

# OAuth2SsoProperties
#security.oauth2.sso:
#  login-path: /login

#ResourceServerProperties
#security.oauth2.resource:
#  clientId: