
# 错误处理相关
server.error.include-stacktrace: on_trace_param
#server.error.path: /error

# template 相关
#spring.thymeleaf.prefix: classpath:/templates/



security.basic.enabled: false
security.user.password: 123456

logging.level.org.springframework.web: INFO
logging.level.org.springframework.security: INFO
logging.level.org.springframework.boot.actuate.audit.listener.AuditListener: DEBUG
logging.level.org.springframework.boot.web.support.ErrorPageFilter: DEBUG
logging.level.org.springframework.web.servlet.view.ContentNegotiatingViewResolver: DEBUG
logging.level.org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping: DEBUG
# https://mongodb.github.io/mongo-java-driver/3.4/driver/reference/logging/
#logging.level.org.mongodb.driver:        TRACE
logging.level.org.mongodb.driver.protocol:  TRACE

# 用来追踪 restTemplate 请求
logging.level.org.apache.http: DEBUG

#spring.devtools.restart.exclude: static/**,public/**,templates/**,resources/**

# MongoProperties
spring.data.mongodb:
  host: localhost
  port: 27017
  database: test
  #username: ''
  #password: ''

# DevToolsProperties
#spring.devtools.restart.additional-paths:
#  - ../data-core/build/libs/
#  - ../data-domain/build/libs/



# RepositoryRestConfiguration
spring.data.rest.basePath: /api


# JacksonProperties
spring.jackson.serialization.write_dates_as_timestamps: false
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
spring.jackson.date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
spring.jackson.joda-date-time-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
spring.jackson.default-property-inclusion: non_null

